[package]
name = "fizz-buzzer"
version = "0.1.0"
edition = "2021"

[lib]
name = "fizz_buzzer"
crate-type = ["cdylib"]

[dependencies]
sha2 = "0.10.8"
hex = "0.4.3"
pyo3 = "0.20.2"

[features]
extension-module = ["pyo3/extension-module"]
